name: Data Schema Code Convention

on:
  push:
    branches:
      - main

jobs:
  sql-linter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install SQLFluff
        run: pip install sqlfluff

      - name: Run SQLFluff
        run: sqlfluff lint DataSchema.sql --dialect postgres
